# Generated by Django 5.0.14 on 2025-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_text", models.TextField()),
                ("solution_text", models.TextField()),
                ("answer_text", models.TextField()),
            ],
        ),
    ]
