# Generated by Django 5.2 on 2025-05-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="source",
            unique_together={("parent", "shortname", "subtitle")},
        ),
    ]
