# Generated by Django 5.0.14 on 2025-04-23 06:13

import django.db.models.deletion
import problems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_alter_problem_number_alter_problem_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="pub_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="source",
            field=models.ForeignKey(
                default=problems.models.Source.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="problems.source",
            ),
        ),
    ]
