# Generated by Django 5.2 on 2025-05-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_alter_source_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
