# Generated by Django 5.0.14 on 2025-04-18 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_problem_contributor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("publish_date", models.DateField(blank=True)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description_text", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="problem",
            name="categories",
            field=models.ManyToManyField(to="problems.category"),
        ),
        migrations.AddField(
            model_name="problem",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.source",
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="technique",
            field=models.ManyToManyField(to="problems.technique"),
        ),
    ]
