# Generated by Django 5.2 on 2025-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_alter_problem_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="problem_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
