# Generated by Django 5.0.14 on 2025-04-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_category_source_technique_problem_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="description_text",
            field=models.TextField(blank=True),
        ),
    ]
