# Generated by Django 5.0.14 on 2025-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="categories",
            field=models.ManyToManyField(blank=True, to="problems.category"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="technique",
            field=models.ManyToManyField(blank=True, to="problems.technique"),
        ),
    ]
