# Generated by Django 5.2 on 2025-05-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_source_problem_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Branch",
        ),
        migrations.AddField(
            model_name="problem",
            name="types",
            field=models.ManyToManyField(
                blank=True, related_name="problems", to="problems.type"
            ),
        ),
    ]
