# Generated by Django 5.0.14 on 2025-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0005_alter_problem_categories_alter_problem_technique"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="subtitle",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
