# Generated by Django 5.0.14 on 2025-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_source_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="problem_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
