# Generated by Django 5.0.14 on 2025-04-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0007_problem_problem_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="problem_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together={("source", "problem_number")},
        ),
    ]
