# Generated by Django 5.0.14 on 2025-04-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0008_alter_problem_problem_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="problem_number",
            new_name="number",
        ),
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together={("source", "number")},
        ),
    ]
