# Generated by Django 5.0.14 on 2025-04-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0009_rename_problem_number_problem_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="numbered_problems",
            field=models.BooleanField(default=True),
        ),
    ]
