# Generated by Django 5.0.14 on 2025-04-19 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0010_source_numbered_problems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="technique",
            new_name="techniques",
        ),
    ]
