# Generated by Django 5.0.14 on 2025-04-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0011_rename_technique_problem_techniques"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="source",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.source",
            ),
            preserve_default=False,
        ),
    ]
