# Generated by Django 5.0.14 on 2025-04-21 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0013_sourcegroup_source_description_source_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="shortname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="problems.source",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="problems.sourcegroup",
            ),
        ),
    ]
