# Generated by Django 5.0.14 on 2025-04-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0014_source_shortname_alter_problem_source_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="description_text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="technique",
            old_name="description_text",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="source",
            name="numbered_problems",
        ),
        migrations.AlterField(
            model_name="problem",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="problems", to="problems.category"
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="number",
            field=models.PositiveSmallIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="problem",
            name="techniques",
            field=models.ManyToManyField(
                blank=True, related_name="problems", to="problems.technique"
            ),
        ),
    ]
