# Generated by Django 5.2.1 on 2025-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
