# Generated by Django 5.2.1 on 2025-05-22 18:30

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 30 characters or fewer. Lowercase letters, digits and underscores(_) only.",
                max_length=18,
                unique=True,
                validators=[accounts.validators.CustomAsciiUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
