# Generated by Django 5.2.1 on 2025-05-22 21:26
# Edited manually

from django.db import migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "group")
    Group.objects.bulk_create([
        Group(name="guest"),
        Group(name="reviewer"),
        Group(name="contributor"),
        Group(name="moderator"),
        Group(name="admin"),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_username"),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
