# Generated by Django 5.2.1 on 2025-05-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftref",
            name="forked_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
