# Generated by Django 5.2.1 on 2025-05-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_alter_draftref_forked_content_type"),
        ("problems", "0014_tag"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="draftproblem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__isnull", False),
                    ("draft_source__isnull", False),
                    _negated=True,
                ),
                name="draft_problem_no_source_duplication",
            ),
        ),
        migrations.AddConstraint(
            model_name="draftsolution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("problem__isnull", False),
                    ("draft_problem__isnull", False),
                    _negated=True,
                ),
                name="draft_solution_no_problem_duplication",
            ),
        ),
        migrations.AddConstraint(
            model_name="draftsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", False),
                    ("draft_parent__isnull", False),
                    _negated=True,
                ),
                name="draft_source_no_parent_duplication",
            ),
        ),
    ]
