# Generated by Django 5.2.1 on 2025-05-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_usersolvedproblem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSolvedProblem",
        ),
    ]
