# Generated by Django 5.2.1 on 2025-06-02 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_text", models.TextField(blank=True, null=True)),
                ("has_answer", models.BooleanField(default=False)),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("number", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=128)),
                ("shortname", models.CharField(blank=True, max_length=40, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "problem_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["parent", "name"],
            },
        ),
        migrations.CreateModel(
            name="SourceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution_text", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="problems.problem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="problem",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="problems.source",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="problems.sourcegroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together={("source", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="source",
            unique_together={("name", "subtitle"), ("shortname", "subtitle")},
        ),
    ]
