# Generated by Django 5.2.1 on 2025-05-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="contributor",
        ),
    ]
