# Generated by Django 5.2.1 on 2025-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_remove_problem_contributor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="source",
            name="shortname",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="subtitle",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="sourcegroup",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="technique",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
