# Generated by Django 5.2.1 on 2025-05-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_alter_branch_name_alter_source_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "Branches"},
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="categories",
            new_name="branches",
        ),
    ]
