# Generated by Django 5.2.1 on 2025-05-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0005_problem_has_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
