# Generated by Django 5.2.1 on 2025-05-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_alter_problem_answer_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="pub_date",
        ),
        migrations.AlterField(
            model_name="problem",
            name="has_answer",
            field=models.BooleanField(default=False),
        ),
    ]
