# Generated by Django 5.2.1 on 2025-05-22 03:27

from django.db import migrations, models


# Gross!
def generate_slugs(apps,schema_editor):
    Source = apps.get_model("problems", "Source")
    for source in Source.objects.all():
        slug_value = ""
        if source.shortname:
             slug_value+=source.shortname
        else:
            slug_value+=source.name
        
        if source.subtitle:
            slug_value+=" "
            slug_value+=source.subtitle
        slug_value = slug_value.replace(" ", "-")
        slug_value = slug_value.replace("#", "")
        slug_value = slug_value.lower()

        source.slug = slug_value
        source.save()



class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0010_alter_historicalproblem_problem_text_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="source",
            unique_together={("name", "subtitle"), ("shortname", "subtitle")},
        ),
        migrations.AddField(
            model_name="historicalsource",
            name="slug",
            field=models.SlugField(default="slugooo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="slug",
            field=models.SlugField(default="slugooo"),
            preserve_default=False,
        ),
        migrations.RunPython(generate_slugs),
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=models.SlugField(unique=True)
        )
    ]
