# Generated by Django 5.2.1 on 2025-05-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "problems",
            "0011_alter_source_unique_together_historicalsource_slug_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsolution",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalsolution",
            name="problem",
        ),
        migrations.RemoveField(
            model_name="historicalsource",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalsource",
            name="parent",
        ),
        migrations.DeleteModel(
            name="HistoricalProblem",
        ),
        migrations.DeleteModel(
            name="HistoricalSolution",
        ),
        migrations.DeleteModel(
            name="HistoricalSource",
        ),
    ]
