# Generated by Django 5.2.1 on 2025-05-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0012_remove_historicalsolution_history_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="branches",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="techniques",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="types",
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
        migrations.DeleteModel(
            name="Technique",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
