# Generated by Django 5.2.1 on 2025-06-02 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproblem",
            name="history_publish_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproblem",
            name="history_publish_reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproblem",
            name="history_publish_type",
            field=models.CharField(
                choices=[("FR", "Force Published"), ("MR", "Merged by review")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsolution",
            name="history_publish_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsolution",
            name="history_publish_reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsolution",
            name="history_publish_type",
            field=models.CharField(
                choices=[("FR", "Force Published"), ("MR", "Merged by review")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsource",
            name="history_publish_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsource",
            name="history_publish_reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsource",
            name="history_publish_type",
            field=models.CharField(
                choices=[("FR", "Force Published"), ("MR", "Merged by review")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalsourcegroup",
            name="history_publish_author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsourcegroup",
            name="history_publish_reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsourcegroup",
            name="history_publish_type",
            field=models.CharField(
                choices=[("FR", "Force Published"), ("MR", "Merged by review")],
                max_length=2,
                null=True,
            ),
        ),
    ]
