# Generated by Django 5.2.1 on 2025-05-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsolution",
            name="history_problem_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_solutions_change",
                to="history.historicalproblem",
            ),
        ),
    ]
