# Generated by Django 5.2.1 on 2025-05-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0003_alter_historicalsolution_history_problem_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsolution",
            name="history_problem_ref",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="history.historicalproblem",
            ),
        ),
    ]
