# Generated by Django 5.2.1 on 2025-05-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0005_historicaldraftproblem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalDraftProblem",
        ),
    ]
